[package]
name = "pokemon-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.3"
show-image = "0.12.3"
hyper = "0.14"
pokemon-api = { path = "../pokemon-api" }